### ISSUE TITLE
ora2pg init_project search ora2pg.conf.dist under Windows

### ISSUE THREAD

**Issue by jmonticolo** [darold/ora2pg#1164]
When I initialize a new ora2pg project, it looks for `ora2pg.conf.dist` file under `C:\ora2pg\`, but the configuration file name is `ora2pg_dist.conf` according to this script line :

https://github.com/darold/ora2pg/blob/8485715e9abd1723e8babb547d2724e1f6a2aeb9/Makefile.PL#L20

I renamed it manually and all works.

**Comment by darold** [comment]
Fixed with commit d1b73cb.

**Comment by moh-hassan** [comment]
The issue is still exist in v23.1 in windows
I had to rename the file ora2pg_conf.dist  to ora2pg.conf.dist

**Comment by darold** [comment]
I guess that modern Windows OS accept two dot in a file name so I have remove the renaming in commit 14dc47c.
