### ISSUE TITLE
DBD::Oracle::db::ora_lob_read: locator is not of type OCILobLocatorPtr 

### ISSUE THREAD

**Issue by fguiet** [darold/ora2pg#175]
Hi Darold,

I am D.Legendre coworker and I am facing this issue while trying to export table with CLOB column.
I am using Orag2Pg v17.1

DBD::Oracle::db::ora_lob_read: locator is not of type OCILobLocatorPtr at /usr/local/share/perl5/Ora2Pg.pm line 10277.
Issuing rollback() due to DESTROY without explicit disconnect() of DBD::Oracle::db handle onemaprod.brgm.fr at /usr/local/share/perl5/Ora2Pg.pm line 10277.

Your truly,
Frederic

**Comment by fguiet** [comment]
Must have read changelog before posting this issue. I think using v17.2 will resolve my problem. I'll let you know asap

**Comment by darold** [comment]
Yes it might have been solved, let me know.

**Comment by fguiet** [comment]
Hi again,

Still no luck with tables contaning CLOB columns with ora2pg v17.2 :

DBD::Pg::db pg_putcopyend failed: ERREUR:  une valeur NULL viole la contrainte NOT NULL de la colonne « code_typeparame »
DETAIL:  La ligne en échec contient (2853, null, 3, Achromobacter, Validé, 2005-01-25 00:00:00, 2015-07-29 14:39:19, SANDRE, Achromobac, Achromobacter, Dénombrement des bactéries du genre "Achromobacter". Bactérie..., null, MAJ : 02092011 ajout de l unité de mesure X, null, 0, null)

ora2pg tries to insert null value in column code_typeparametre while all data in Oracle source column are filled with a value...bad mapping?

**Comment by fguiet** [comment]
For information, here is the definition of the Oracle table

Header ***Column name*** ***Null/not null*** ***Type***
CDPARAMETRE	N	VARCHAR2 (5 Char)
CODE_TYPEPARAME	N	VARCHAR2 (1 Char)
CODE_NATUREPARA	N	VARCHAR2 (1 Char)
NOMPARAMETRE	N	VARCHAR2 (255 Char)
STPARAMETRE	N	VARCHAR2 (20 Char)
DATECREATIONPARAMETRE	N	DATE
DATEMAJPARAMETRE	N	DATE
AUTEURPARAMETRE	N	VARCHAR2 (50 Char)
LBCOURTPARAMETRE	Y	VARCHAR2 (10 Char)
LBLONGPARAMETRE	Y	VARCHAR2 (25 Char)
DFPARAMETRE	Y	CLOB
REFERENCEPARAMETRE	Y	CLOB
COMPARAMETRE	Y	CLOB
NOMINTPARAMETRE	Y	VARCHAR2 (255 Char)
PARAMETRECALCULE	N	INTEGER
DSCALCULPARSYNTHESE	Y	CLOB

**Comment by darold** [comment]
Ok I found the bug, will be fixed asap.

**Comment by fguiet** [comment]
Think I find the bug : all values with 0 are replace with \n

**Comment by fguiet** [comment]
COPY fraction (cdfractionanalysee,code_naturefrac,cdsupport_support,lbfractionanalysee,stfractionanalysee,datemajfractionanlysee,datecreationfractionanalysee,auteurfractionanalysee,comfractionanalysee,nomintfractionanalysee) FROM STDIN;
\N	1	\N	Fraction analysée inconnue	Validé	1995-07-21 00:00:00	1994-01-01 00:00:00	Ministère de l'Environnement	\N	\N

should be

COPY fraction (cdfractionanalysee,code_naturefrac,cdsupport_support,lbfractionanalysee,stfractionanalysee,datemajfractionanlysee,datecreationfractionanalysee,auteurfractionanalysee,comfractionanalysee,nomintfractionanalysee) FROM STDIN;
0	1	0	Fraction analysée inconnue	Validé	1995-07-21 00:00:00	1994-01-01 00:00:00	Ministère de l'Environnement	\N	\N

**Comment by darold** [comment]
Please update to latest development code, commit db04648 might solves this major issue.
Let me now.

**Comment by fguiet** [comment]
Tried again and...it worked!!! Merci beaucoup pour ta réactivité Darold! 
You close this issue?

**Comment by fguiet** [comment]
Found another bug but this is due to my data...see line with number 762736. There is CR after SURAN and this CR causes the following error : DBD::Pg::db pg_putcopyend failed: ERREUR:  données manquantes pour la colonne « idoriginepoint »

762734	\N	12	100	5	01	3.1	414628	06057200	776340	2095470	231	arbresle	6057200
762735	\N	12	100	5	01	3.1	414636	06057700	785225	2104925	172	lucenay	6057700
762736	\N	12	100	5	01	3.1	\N	60580653	\N	\N	240	SURAN 
� Neuville sur Ain	60580653
762737	\N	12	100	5	01	3.1	414648	06059100	0	0	248	Ruisseau des Echets � Fleurieu sur Sa�ne	6059100
762738	\N	12	100	5	01	3.1	414649	06059500	793984	2091550	163	lyon	6059500

**Comment by fguiet** [comment]
This type of value in character column  
"d'Orbigny, 1842 	" 
is not correctly handled as well.
DBD::Pg::db pg_putcopyend failed: ERREUR:  données supplémentaires après la dernière colonne attendue

It introduces a extra column...and obviously insert failed after that

**Comment by darold** [comment]
Good catch, this is not your data, this is an other regression in Ora2Pg 17.2. Commit a78aa9f fix that issue.

Regards,

**Comment by darold** [comment]
Release 17.3 published including those fixes.
