### ISSUE TITLE
Problem with exporting nullable number types

### ISSUE THREAD

**Issue by barabaka** [darold/ora2pg#206]
I am getting the following error for NUMBER columns that contain null values.
DBD::Pg::st execute failed: ERROR:  invalid input syntax for integer: "NULL" at C:/Strawberry/perl/site/lib/Ora2Pg.pm line 10691.

Oracle type: IMAGE_ID NUMBER(19)
Converted type: image_id bigint

**Comment by darold** [comment]
Please upgrade to latest development code, this issue is already fixed.

**Comment by barabaka** [comment]
I updated to the latest commit from master, rebuilt the module, but I am still getting this issue. I have Oracle 11g and PostgreSQL 9.5

**Comment by darold** [comment]
Thanks, last commit f6348d8 might fix this issue. You may want to use COPY action to export your data, using INSERT is very slow.

Let me know if that's fully solves your issue.

**Comment by barabaka** [comment]
Thanks @darold, works now!
