### ISSUE TITLE
Error during partitionned tables COPY 

### ISSUE THREAD

**Issue by NicolasMartin69** [darold/ora2pg#246]
Hi, 
We have an issue when we try to COPY datas from Oracle RDBMS partitionned tables to postgresql :

Here is the error message : 
```
Dumping partition table PROP_TER.TER_DETAIL_P3_FACTURE...
Looking how to retrieve data from PROP_TER.TER_DETAIL_P3_FACTURE partition P2012_10...
DEBUG: cloning Oracle database connection.
Fetching all data from P2012_10 tuples...
Dumping data from table P2012_10 into PostgreSQL...
Setting client_encoding to UTF8...
Disabling synchronous commit when writing to PostgreSQL...
DEBUG: Formatting bulk of 200000 data for PostgreSQL.
DEBUG: Creating output for 200000 tuples
DEBUG: Sending COPY bulk output directly to PostgreSQL backend
DBD::Pg::db do failed: ERROR:  relation "p2012_10" does not exist at /applis/ora2pg/ora2pg-master/blib/lib/Ora2Pg.pm line 11013.
FATAL: ERROR:  relation "p2012_10" does not exist
DBD::Oracle::db disconnect failed: ORA-03135: connection lost contact
Process ID: 0
Session ID: 44 Serial number: 2171 (DBD ERROR: OCISessionEnd) at /applis/ora2pg/ora2pg-master/blib/lib/Ora2Pg.pm line 10304.
Aborting export...
```

The command is : 
`ora2pg --pg_dsn "dbi:Pg:dbname=${PGDATABASE};host=${PGHOST};port=${PGPORT}" --pg_user ${PG_USER} -c ./config/ora2pg.conf -t COPY -v
`
The version we use is the following : Ora2Pg v17.5

Regards,
Nicolas

**Comment by darold** [comment]
Hi,

Have you imported the partitions before?
```
  mkdir partitions/
  ora2pg -t PARTITION -c ora2pg.conf -o partition.sql -b partitions
  psql mydb -f partitions/partition.sql
```

**Comment by NicolasMartin69** [comment]
Hi, 
Yes partitions have been created.
```

[oracle@x64lmwbinlj TERP]$ psql -h ${PGHOST} -p ${PGPORT} -U ${PG_USER} -d ora2pg
psql (9.4.5)
Type "help" for help.

ora2pg=# set search_path="$user",public,prop_ter;
SET
ora2pg=# \dt
                     List of relations
  Schema  |             Name             | Type  |  Owner
----------+------------------------------+-------+----------
 prop_ter | fti_acteur_gestion           | table | prop_ter
 prop_ter | fti_axe_central_bi           | table | prop_ter
 prop_ter | fti_domaine                  | table | prop_ter
 prop_ter | fti_facture                  | table | prop_ter
 prop_ter | fti_forfait_prestation_p3    | table | prop_ter
 prop_ter | fti_forfait_service_de_gare  | table | prop_ter
 prop_ter | fti_idtgv_repartition        | table | prop_ter
 prop_ter | fti_inventaire               | table | prop_ter
 prop_ter | fti_iprod_acquisition        | table | prop_ter
 prop_ter | fti_ligne_facture            | table | prop_ter
 prop_ter | fti_ligne_facture_tmp        | table | prop_ter
 prop_ter | fti_produit_bi               | table | prop_ter
 prop_ter | fti_ref_sop_psoft            | table | prop_ter
 prop_ter | fti_regularisation           | table | prop_ter
 prop_ter | fti_restit_facture           | table | prop_ter
 prop_ter | fti_segment                  | table | prop_ter
 prop_ter | fti_seuil                    | table | prop_ter
 prop_ter | p2011_01                     | table | prop_ter
 prop_ter | p2011_02                     | table | prop_ter
 prop_ter | p2011_03                     | table | prop_ter
 prop_ter | p2011_04                     | table | prop_ter
 prop_ter | p2011_05                     | table | prop_ter
 prop_ter | p2011_06                     | table | prop_ter
 prop_ter | p2011_07                     | table | prop_ter
 prop_ter | p2011_08                     | table | prop_ter
 prop_ter | p2011_09                     | table | prop_ter
 prop_ter | p2011_10                     | table | prop_ter
 prop_ter | p2011_11                     | table | prop_ter
 prop_ter | p2011_12                     | table | prop_ter
 prop_ter | p2012_01                     | table | prop_ter
 prop_ter | p2012_02                     | table | prop_ter
 prop_ter | p2012_03                     | table | prop_ter
 prop_ter | p2012_04                     | table | prop_ter
 prop_ter | p2012_05                     | table | prop_ter
 prop_ter | p2012_06                     | table | prop_ter
 prop_ter | p2012_07                     | table | prop_ter
 prop_ter | p2012_08                     | table | prop_ter
 prop_ter | p2012_09                     | table | prop_ter
 prop_ter | p2012_10                     | table | prop_ter
```

**Comment by darold** [comment]
Ok, I see, the problem seems that the partition names is not prefixed by the schema name. To fix that you can change the default search_path of the user:

    ALTER USER myuser SET search_path="$user",public,prop_ter;

that should fix the issue on your side.

**Comment by NicolasMartin69** [comment]
Hi, that didn't resolve my issue (just to be sure I've recreated my partitions with PREFIX) : 

```
Dumping partition table PROP_TER.TER_DETAIL_P3_FACTURE...
Looking how to retrieve data from PROP_TER.TER_DETAIL_P3_FACTURE partition P2015_11...
DEBUG: cloning Oracle database connection.
Fetching all data from P2015_11 tuples...
Dumping data from table P2015_11 into PostgreSQL...
Setting client_encoding to UTF8...
Disabling synchronous commit when writing to PostgreSQL...
DEBUG: Formatting bulk of 200000 data for PostgreSQL.
DEBUG: Creating output for 200000 tuples
DEBUG: Sending COPY bulk output directly to PostgreSQL backend
DBD::Pg::db do failed: ERROR:  relation "prop_ter.ter_detail_p3_facture_p2015_11" does not exist at /applis/ora2pg/ora2pg-master/blib/lib/Ora2Pg.pm line 11013.
FATAL: ERROR:  relation "prop_ter.ter_detail_p3_facture_p2015_11" does not exist
DBD::Oracle::db disconnect failed: ORA-03135: connection lost contact
Process ID: 0
Session ID: 299 Serial number: 1825 (DBD ERROR: OCISessionEnd) at /applis/ora2pg/ora2pg-master/blib/lib/Ora2Pg.pm line 10304.
Aborting export...

[oracle@x64lmwbinlj TERP]$ psql -h ${PGHOST} -p ${PGPORT} -U ${PG_USER} -d ora2pg
psql (9.4.5)
Type "help" for help.

ora2pg=# \d prop_ter.ter_detail_p3_facture_p2015_11
   Table "prop_ter.ter_detail_p3_facture_p2015_11"
   Column   |            Type             | Modifiers
------------+-----------------------------+-----------
 exercice   | smallint                    | not null
 date_jour  | timestamp without time zone | not null
 tt0020     | character varying(3)        | not null
 segment    | character varying(2)        | not null
 code_tct   | character varying(3)        | not null
 num_marche | character varying(6)        | not null
 num_p3     | smallint                    | not null
 nb_uo      | integer                     | not null
 tarif      | double precision            |
Check constraints:
    "ter_detail_p3_facture_p2015_11_date_jour_check" CHECK (date_jour >= to_date(' 2015-11-01 00:00:00'::text, 'SYYYY-MM-DD HH24:MI:SS'::text) AND date_jour < to_date(' 2015-12-01 00:00:00'::text, 'SYYYY-MM-DD HH24:MI:SS'::text))
In
herits: ter_detail_p3_facture

ora2pg=# show search_path;
        search_path
---------------------------
 "$user", public, prop_ter
(1 row)
```

Regards,
Nicolas

**Comment by darold** [comment]
I'm not able to reproduce this issue. The only things that can generate this kind of issue is when PRESERVE_CASE is enabled during data export and was not during the creation of the tables, or you are not connecting to the same host/database.

**Comment by NicolasMartin69** [comment]
Hi, sorry, that was only my fault, I recreate the whole database and now all was fine.
