### ISSUE TITLE
ORA-01741 while exporting materializad views

### ISSUE THREAD

**Issue by threenotrump** [darold/ora2pg#426]
DBD::Oracle::db prepare failed: ORA-01741: illegal zero-length identifier (DBD ERROR: OCIStmtPrepare) at /usr/local/share/perl5/Ora2Pg.pm line 11094.

I am getting this error while exporting a materialized view  as a table and tables with types as columns.

I am using owner as oracle user and this user has dba priviliges.

Is there a way to workaround?

My oracle db version is 11.2.0.4.0

Ora2pg version is v18.1

**Comment by darold** [comment]
Please try again with NO_LO_LOCATOR disabled, I mean set the configuration directive to 0 in your ora2pg.conf. Let me know.

**Comment by threenotrump** [comment]
Hi Darold.

Thank you very much for the fast response but despite setting NO_LOB_LOCATOR to 0 nothing changed.

I am still getting the same error.

**Comment by darold** [comment]
Please post the Oracle materialized view and related tables DDL code. If you can not post here, you can send it to my private email gilles _AT_ darold _DOT_ net

**Comment by threenotrump** [comment]
Hi Darold

I ve sent the DDLs

**Comment by darold** [comment]
Thanks for the DDLs, I've just fixed the error in commit 9549b53 to prevent trying to export data from a non existing table. Note that even if it solve the error it will not solves your issue as this is not possible to export a materialized view as table. You have to create the tables and import data, then export the materialized view DDL to transform it as a table.

**Comment by threenotrump** [comment]
Hi Darold 

It solved materialized view table problem but it didnt solve type based table.

Am I doing something wrong?

**Comment by darold** [comment]
Please check that commit ca981ca solves this issue.

**Comment by darold** [comment]
Finally I think I've got it. Commit 51883bf fixes unwanted and broken export of tables created with `CREATE TABLE tablename OF objType`.

**Comment by threenotrump** [comment]
Hi Darold

I am sorry for the last response. I was on vacation.

I am still getting the same error.

I am uninstalling old ora2pg by the commands output of make uninstall and install the last version of ora2pg.

Am I doign something wrong?

**Comment by TWAC** [comment]
I have this problem on 18.2 and git master.

I logged the query leading to this by adding logging [here](https://github.com/darold/ora2pg/blob/81032545ac75df633def67e25ed709ad3dd50ee0/lib/Ora2Pg.pm#L12464).
```perl
$self->logit("query: $query\n", 0, 0);
```

I have changed the config file like this.
```diff
--- ora2pg_dist.conf
+++ ora2pg-my.conf
@@ -33 +33 @@
-DEBUG		0
+DEBUG		1
@@ -46 +46 @@
-EXPORT_SCHEMA	0
+EXPORT_SCHEMA	1
@@ -152 +152 @@
-TYPE		TABLE
+TYPE		MVIEW,COPY
@@ -176 +176 @@
-#VIEW_AS_TABLE	VIEW_NAME
+VIEW_AS_TABLE	.*
@@ -430 +430 @@
-FKEY_DEFERRABLE	0
+FKEY_DEFERRABLE	1
@@ -440 +440 @@
-DEFER_FKEY	0
+DEFER_FKEY	1
@@ -668 +668 @@
-PG_INTEGER_TYPE	1
+PG_INTEGER_TYPE	0
@@ -802 +802 @@
-TRANSACTION	serializable
+TRANSACTION	committed
@@ -838 +838 @@
-NO_LOB_LOCATOR  1
+NO_LOB_LOCATOR  0

```

the logfile contains this:
```
Ora2Pg version: 18.2
Trying to connect to database: dbi:Oracle:host=myhost;sid=mysid;port=1521
Isolation level: SET TRANSACTION ISOLATION LEVEL READ COMMITTED
Looking forward functions declaration in all schema.
Looking at package utility...
Retrieving materialized views information...
[1] Scanning MYSCHEMA.MYTABLEa...
[2] Scanning MYSCHEMA.MYTABLEb...

...

Retrieving table information...
[1] Scanning table MYSCHEMA.MYTABLEx (0 rows)...
[2] Scanning table MYSCHEMA.MYTABLEy (0 rows)...
View MYSCHEMA.MYVIEWa column aliases:
View MYSCHEMA.MYVIEWb column aliases:

...

Scanning view MYSCHEMA.MYVIEWa to export as table...
Scanning view MYSCHEMA.MYVIEWb to export as table...

...

Add materialized views definition...
	Adding materialized view MYSCHEMA.MYTABLEa...
	Adding materialized view MYSCHEMA.MYTABLEb...

...

Trying to connect to database: dbi:Oracle:host=myhost;sid=mysid;port=1521
Isolation level: SET TRANSACTION ISOLATION LEVEL READ COMMITTED
Retrieving partitions information...


Looking how to retrieve data from MYSCHEMA.MYVIEWa...
Data type  is not native, searching on custom types.
Data type  is not native, searching on custom types.
Data type  is not native, searching on custom types.
Data type  is not native, searching on custom types.
Data type  is not native, searching on custom types.
Data type  is not native, searching on custom types.
Data type  is not native, searching on custom types.
query: SELECT "","","","","","","" FROM "MYSCHEMA"."MYVIEWa" a
FATAL: _extract_data() ORA-01741: illegal zero-length identifier (DBD ERROR: OCIStmtPrepare)
```

**Comment by darold** [comment]
Please do not use COPY with other export type this is not recommended and could lead to strange behaviors like this one. Use `TYPE    MVIEW` in your configuration file or `-t MVIEW` at command line, then use `-t COPY` in an other ora2pg call.

Let me know if you still have the same issue.

**Comment by TWAC** [comment]
The -t MVIEW call exited fine, but the -t COPY call hits the same problem.
```
Ora2Pg version: 18.2
Trying to connect to database: dbi:Oracle:host=myhost;sid=mysid;port=1521
Isolation level: SET TRANSACTION ISOLATION LEVEL READ COMMITTED
Retrieving table information...
[1] Scanning table MYSCHEMA.MYTABLEx (0 rows)...
[2] Scanning table MYSCHEMA.MYTABLEy (0 rows)...
View MYSCHEMA.MYVIEWa column aliases:
View MYSCHEMA.MYVIEWb column aliases:

...

Scanning view MYSCHEMA.MYVIEWa to export as table...
Scanning view MYSCHEMA.MYVIEWb to export as table...

...

Trying to connect to database: dbi:Oracle:host=myhost;sid=mysid;port=1521
Isolation level: SET TRANSACTION ISOLATION LEVEL READ COMMITTED
Retrieving partitions information...


Looking how to retrieve data from MYSCHEMA.MYVIEWa...
Data type  is not native, searching on custom types.
Data type  is not native, searching on custom types.
Data type  is not native, searching on custom types.
Data type  is not native, searching on custom types.
Data type  is not native, searching on custom types.
Data type  is not native, searching on custom types.
Data type  is not native, searching on custom types.
query: SELECT "","","","","","","" FROM "MYSCHEMA"."MYVIEWa" a
FATAL: _extract_data() ORA-01741: illegal zero-length identifier (DBD ERROR: OCIStmtPrepare)
```

**Comment by darold** [comment]
I can't reproduce this issue despite several tests, can you send me the DDL to reproduce your custom type, source(s) table(s) and the view that fail?
