### ISSUE TITLE
broken declaration in triggers related to FOR cycle controll variables

### ISSUE THREAD

**Issue by okbob** [darold/ora2pg#452]
Oracle trigger:
<pre>
declare
  -- local variables here
begin
  IF 
     (:new.CVZNIKRADK <>'P') 
      THEN
     --- 21.2.2014 generovat pouze metody , ktere se netykaji polozky najem a vybaveni prostoru 
     FOR qBudo IN
      (
      SELECT ID_CNAJVYPPOL,ID_SKUP_CISEL
      FROM CNAJVYPPOL WHERE ID_SKUP_CISEL = :new.ID_SKUP_CISEL
      and trim(kod_cnajvyppol) not 
      in ('S','A','C','D','F','G','H','K','PL','RN','SLEVA107','VYPO','ZP')
       )

    LOOP
         Insert into CISVPOLVYP (ID_POLONAJ,ID_CNAJVYPPOL,ID_SKUP_CISEL,LIDENT)
         Values (:new.ID_POLONAJ,qBudo.ID_CNAJVYPPOL,qBudo.ID_SKUP_CISEL,:new.LIDENT);   
    
    END LOOP;
      
   END IF;
end CISPOLPRE_AI;
</pre>

Ora2pg result:
<pre>
CREATE OR REPLACE FUNCTION public.trigger_fct_cispolpre_ai()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  qBudo RECORD;
  -- local variables here
DECLARE

  qBudo RECORD;

BEGIN
  IF (NEW.CVZNIKRADK <>'P')
      THEN
     --- 21.2.2014 generovat pouze metody , ktere se netykaji polozky najem a vybaveni prostoru
     FOR qBudo IN (
      SELECT ID_CNAJVYPPOL,ID_SKUP_CISEL
      FROM CNAJVYPPOL WHERE ID_SKUP_CISEL = NEW.ID_SKUP_CISEL
      and btrim(kod_cnajvyppol) not
      in ('S','A','C','D','F','G','H','K','PL','RN','SLEVA107','VYPO','ZP')
       )

    LOOP
         Insert into CISVPOLVYP(ID_POLONAJ,ID_CNAJVYPPOL,ID_SKUP_CISEL,LIDENT)
         Values (NEW.ID_POLONAJ,qBudo.ID_CNAJVYPPOL,qBudo.ID_SKUP_CISEL,NEW.LIDENT);

    END LOOP;

   END IF;
RETURN NEW;
end
$function$
</pre>
Note: PL/SQL, PLpgSQL too allows empty DECLARE part

Similar errors:
Oracle:
<pre>
TRIGGER "IDES_JMMAJ".CISUJEDN_AI AFTER INSERT
  ON CISUJEDN
  FOR EACH ROW
 

DECLARE

mTEXTChyba varchar2(4000);

BEGIN
  
  --- REN 23.01.2012  - VYNECHANA ROLE  SDRUZENI , A RAJONY PRES UCETNI JEDNOTKU
  IF :new.CVZNIKRADK <> 'P' THEN
      
     IF nvl(:new.GEN_RAJONISTY,'N') = 'N' THEN
       FOR qRajon IN
       ( SELECT ID_SSSRAJON
           FROM SSSRAJON MT , SSSROLE A1
           WHERE ( MT.ID_ASPRAVCE = :new.ID_ASPRAVCE ) 
             AND (( TRIM(A1.KOD_ROLE) = 'SPRAVCE') OR ( TRIM(A1.KOD_ROLE) = 'VEDOUC'))
             AND NVL(UCE_PRES_JEDN,'N') = 'N'
             AND MT.ID_ROLE = A1.ID_ROLE )
       LOOP
          INSERT INTO SSSVRAJJED( ID_CISUJEDN ,ID_SSSRAJON ,ID_ASPRAVCE , ID_APROVOZNA , LIDENT , CVZNIKRADK ,PLATNOST_OD )
            VALUES ( :new.ID_CISUJEDN , qRajon.ID_SSSRAJON , :new.ID_ASPRAVCE , :new.ID_APROVOZNA , :new.LIDENT , :new.CVZNIKRADK ,:new.PLATNOST_OD );
            
       END LOOP;
         
       FOR qRajon IN
       ( SELECT ID_SSSRAJON
           FROM SSSRAJON MT , SSSROLE A1
           WHERE ( MT.ID_ASPRAVCE = :new.ID_ASPRAVCE ) 
             AND ( TRIM(A1.KOD_ROLE) = 'DES') 
             AND NVL(UCE_PRES_JEDN,'N') = 'N'
             AND MT.ID_ROLE = A1.ID_ROLE )
       LOOP
          INSERT INTO SSSVRAJJED( ID_CISUJEDN ,ID_SSSRAJON ,ID_ASPRAVCE , ID_APROVOZNA , LIDENT , CVZNIKRADK ,PLATNOST_OD )
            VALUES ( :new.ID_CISUJEDN , qRajon.ID_SSSRAJON , :new.ID_ASPRAVCE , :new.ID_APROVOZNA , :new.LIDENT , :new.CVZNIKRADK ,:new.PLATNOST_OD );
            
       END LOOP;
     ELSE
       FOR qRajon IN
       ( SELECT ID_SSSRAJON
           FROM SSSRAJON MT , SSSROLE A1
           WHERE ( MT.ID_ASPRAVCE = :new.ID_ASPRAVCE ) 
             AND ( TRIM(A1.KOD_ROLE) <> 'SDRUZENI') 
             AND MT.ID_APROVOZNA IS NULL
             AND NVL(UCE_PRES_JEDN,'N') = 'N'
             AND MT.ID_ROLE = A1.ID_ROLE )

       LOOP
          INSERT INTO SSSVRAJJED( ID_CISUJEDN ,ID_SSSRAJON ,ID_ASPRAVCE , ID_APROVOZNA , LIDENT , CVZNIKRADK ,PLATNOST_OD )
            VALUES ( :new.ID_CISUJEDN , qRajon.ID_SSSRAJON , :new.ID_ASPRAVCE , :new.ID_APROVOZNA , :new.LIDENT , :new.CVZNIKRADK ,:new.PLATNOST_OD );
            
       END LOOP;
         
       FOR qRajon IN
       ( SELECT ID_SSSRAJON
           FROM SSSRAJON MT , SSSROLE A1
           WHERE ( MT.ID_APROVOZNA = :new.ID_APROVOZNA ) 
             AND ( TRIM(A1.KOD_ROLE) <> 'SDRUZENI') 
             AND NVL(UCE_PRES_JEDN,'N') = 'N'
             AND MT.ID_ROLE = A1.ID_ROLE )

       LOOP
          INSERT INTO SSSVRAJJED( ID_CISUJEDN ,ID_SSSRAJON ,ID_ASPRAVCE , ID_APROVOZNA , LIDENT , CVZNIKRADK ,PLATNOST_OD )
            VALUES ( :new.ID_CISUJEDN , qRajon.ID_SSSRAJON , :new.ID_ASPRAVCE , :new.ID_APROVOZNA , :new.LIDENT , :new.CVZNIKRADK ,:new.PLATNOST_OD );
            
       END LOOP;

     
     END IF;

  END IF;

END;
</pre>

Ora2pg:
<pre>
CREATE OR REPLACE FUNCTION public.trigger_fct_cisujedn_ai()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  qRajon RECORD;

mTEXTChyba varchar(4000);DECLARE

  qRajon RECORD;

BEGIN

  --- REN 23.01.2012  - VYNECHANA ROLE  SDRUZENI , A RAJONY PRES UCETNI JEDNOTKU
  IF NEW.CVZNIKRADK <> 'P' THEN

     IF coalesce(NEW.GEN_RAJONISTY,'N') = 'N' THEN
       FOR qRajon IN
       ( SELECT ID_SSSRAJON
           FROM SSSRAJON MT , SSSROLE A1
           WHERE ( MT.ID_ASPRAVCE = NEW.ID_ASPRAVCE )
             AND (( btrim(A1.KOD_ROLE) = 'SPRAVCE') OR ( btrim(A1.KOD_ROLE) = 'VEDOUC'))
             AND coalesce(UCE_PRES_JEDN,'N') = 'N'
             AND MT.ID_ROLE = A1.ID_ROLE )
       LOOP
          INSERT INTO SSSVRAJJED( ID_CISUJEDN ,ID_SSSRAJON ,ID_ASPRAVCE , ID_APROVOZNA , LIDENT , CVZNIKRADK ,PLATNOST_OD )
            VALUES ( NEW.ID_CISUJEDN , qRajon.ID_SSSRAJON , NEW.ID_ASPRAVCE , NEW.ID_APROVOZNA , NEW.LIDENT , NEW.CVZNIKRADK ,NEW.PLATNOST_OD );

       END LOOP;

       FOR qRajon IN ( SELECT ID_SSSRAJON
           FROM SSSRAJON MT , SSSROLE A1
           WHERE ( MT.ID_ASPRAVCE = NEW.ID_ASPRAVCE )
             AND ( btrim(A1.KOD_ROLE) = 'DES')
             AND coalesce(UCE_PRES_JEDN,'N') = 'N'
             AND MT.ID_ROLE = A1.ID_ROLE )
       LOOP
          INSERT INTO SSSVRAJJED( ID_CISUJEDN ,ID_SSSRAJON ,ID_ASPRAVCE , ID_APROVOZNA , LIDENT , CVZNIKRADK ,PLATNOST_OD )
            VALUES ( NEW.ID_CISUJEDN , qRajon.ID_SSSRAJON , NEW.ID_ASPRAVCE , NEW.ID_APROVOZNA , NEW.LIDENT , NEW.CVZNIKRADK ,NEW.PLATNOST_OD );

       END LOOP;
     ELSE
       FOR qRajon IN ( SELECT ID_SSSRAJON
           FROM SSSRAJON MT , SSSROLE A1
           WHERE ( MT.ID_ASPRAVCE = NEW.ID_ASPRAVCE )
             AND ( btrim(A1.KOD_ROLE) <> 'SDRUZENI')
             AND MT.ID_APROVOZNA IS NULL
             AND coalesce(UCE_PRES_JEDN,'N') = 'N'
             AND MT.ID_ROLE = A1.ID_ROLE )

       LOOP
          INSERT INTO SSSVRAJJED( ID_CISUJEDN ,ID_SSSRAJON ,ID_ASPRAVCE , ID_APROVOZNA , LIDENT , CVZNIKRADK ,PLATNOST_OD )
            VALUES ( NEW.ID_CISUJEDN , qRajon.ID_SSSRAJON , NEW.ID_ASPRAVCE , NEW.ID_APROVOZNA , NEW.LIDENT , NEW.CVZNIKRADK ,NEW.PLATNOST_OD );

       END LOOP;

       FOR qRajon IN ( SELECT ID_SSSRAJON
           FROM SSSRAJON MT , SSSROLE A1
           WHERE ( MT.ID_APROVOZNA = NEW.ID_APROVOZNA )
             AND ( btrim(A1.KOD_ROLE) <> 'SDRUZENI')
             AND coalesce(UCE_PRES_JEDN,'N') = 'N'
             AND MT.ID_ROLE = A1.ID_ROLE )

       LOOP
          INSERT INTO SSSVRAJJED( ID_CISUJEDN ,ID_SSSRAJON ,ID_ASPRAVCE , ID_APROVOZNA , LIDENT , CVZNIKRADK ,PLATNOST_OD )
            VALUES ( NEW.ID_CISUJEDN , qRajon.ID_SSSRAJON , NEW.ID_ASPRAVCE , NEW.ID_APROVOZNA , NEW.LIDENT , NEW.CVZNIKRADK ,NEW.PLATNOST_OD );

       END LOOP;

     END IF;

  END IF;

RETURN NEW;
END
$function$
</pre>
It looks so Ora2pg try to declare FOR variable any time when it is used - what is impossible. Maybe safer technique can be using one special block for any FOR like
<pre>
-- Oracle
FOR x IN ...
LOOP
END LOOP

-- Postgres
DECLARE x RECORD;
BEGIN -- explicitly created for FOR
  FOR x IN ..
  END LOOP;
END;
</pre>

**Comment by darold** [comment]
The two last commit 742f17c and 8748af1 might fix this issue.

**Comment by okbob** [comment]
It is better, but not fully correct. Now the control variable is missing sometimes. 
<pre>
TRIGGER "IDES_JMMAJ".OBPODBMI_BD BEFORE DELETE
ON  OBPODBMI
FOR EACH ROW
DECLARE
  mSql VARCHAR2(4);

BEGIN

  FOR qAdr IN
    ( SELECT ID_ADR FROM OBPVOMAD WHERE ID_ODBMISTO = :old.ID_ODBMISTO )
  LOOP
    DELETE FROM OBPVOMAD WHERE ID_ODBMISTO = :old.ID_ODBMISTO;
    
    begin
    DELETE FROM PARADR WHERE ID_ADR = qAdr.ID_ADR;
    exception 
     when others then 
     mSql :='A';
    end;
      
  END LOOP;  
         
         
  DELETE FROM OBPVOMOB WHERE ID_ODBMISTO = :old.ID_ODBMISTO;
  DELETE FROM OBPVKPOM WHERE ID_ODBMISTO = :old.ID_ODBMISTO;
  DELETE FROM OBPVODMPRA WHERE ID_ODBMISTO = :old.ID_ODBMISTO;
  DELETE FROM UDRVODMODB where ID_ODBMISTO = :old.ID_ODBMISTO;
  ---zruseni vazby v uce
  /*
  update ucepohyb set id_odbmisto = NULL where ID_ODBMISTO = :old.ID_ODBMISTO;
  update UCESALDOPOL set id_odbmisto = NULL where ID_ODBMISTO = :old.ID_ODBMISTO;
  */
  --- zruseni vazby na prvky
  update obpprvky set id_odbmisto = NULL where ID_ODBMISTO = :old.ID_ODBMISTO;

END ;
</pre>

Ora2pg result:
<pre>
CREATE OR REPLACE FUNCTION public.trigger_fct_obpodbmi_bd()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
AS $function$
DECLARE
  mSql varchar(4);
BEGIN
  BEGIN

  FOR qAdr IN ( SELECT ID_ADR FROM OBPVOMAD WHERE ID_ODBMISTO = OLD.ID_ODBMISTO )
  LOOP
    DELETE FROM OBPVOMAD WHERE ID_ODBMISTO = OLD.ID_ODBMISTO;

    BEGIN
    DELETE FROM PARADR WHERE ID_ADR = qAdr.ID_ADR;
    exception
     when others then 
     mSql :='A';
    end;

  END LOOP;
         
         
  DELETE FROM OBPVOMOB WHERE ID_ODBMISTO = OLD.ID_ODBMISTO;
  DELETE FROM OBPVKPOM WHERE ID_ODBMISTO = OLD.ID_ODBMISTO;
  DELETE FROM OBPVODMPRA WHERE ID_ODBMISTO = OLD.ID_ODBMISTO;
  DELETE FROM UDRVODMODB where ID_ODBMISTO = OLD.ID_ODBMISTO;
  ---zruseni vazby v uce
  /*
  update ucepohyb set id_odbmisto = NULL where ID_ODBMISTO = :old.ID_ODBMISTO;
  update UCESALDOPOL set id_odbmisto = NULL where ID_ODBMISTO = :old.ID_ODBMISTO;
  */
  --- zruseni vazby na prvky
  update obpprvky set id_odbmisto  = NULL where ID_ODBMISTO = OLD.ID_ODBMISTO;

  END;
RETURN OLD;
END
$function$
</pre>

**Comment by darold** [comment]
Solved with commit 1bf3865

**Comment by okbob** [comment]
This case is fixed - but I found another
<pre>
TRIGGER "IDES_JMMAJ".UCEPOLBAN_BD
  before delete on ucepolban
  for each row

declare
  -- local variables here
begin
    DELETE FROM UCEVCLEBAN  WHERE ID_UCEPOLBAN = :old.ID_UCEPOLBAN;
    DELETE FROM UCEVAZBA  WHERE ID_UCEPOLBAN = :old.ID_UCEPOLBAN;
    DELETE FROM UCEVBANLOK WHERE ID_UCEPOLBAN = :old.ID_UCEPOLBAN;
    DELETE FROM UCEVFAKVYU WHERE ID_UCEPOLBAN = :old.ID_UCEPOLBAN;
    DELETE FROM UCEBANPOD WHERE ID_UCEPOLBAN = :old.ID_UCEPOLBAN;
    
    FOR qNAJAVPIPR IN
      ( SELECT ID_NAJAVPIPR
          FROM NAJAVPIPR
          WHERE ID_UCEPOLBAN = :old.ID_UCEPOLBAN )
    LOOP
      UPDATE NAJAVPIPR
        SET ID_UCEPOLBAN = NULL
        WHERE ID_NAJAVPIPR = qNAJAVPIPR.ID_NAJAVPIPR;
    END LOOP;


end UCEPOLBAN_BD;
</pre>

Ora2pg:
<pre>
        CREATE OR REPLACE FUNCTION public.trigger_fct_ucepolban_bd()
         RETURNS trigger
         LANGUAGE plpgsql
         SECURITY DEFINER
1       AS $function$
2       declare
3         -- local variables here
4       BEGIN
5           DELETE FROM UCEVCLEBAN  WHERE ID_UCEPOLBAN = OLD.ID_UCEPOLBAN;
6           DELETE FROM UCEVAZBA  WHERE ID_UCEPOLBAN = OLD.ID_UCEPOLBAN;
7           DELETE FROM UCEVBANLOK WHERE ID_UCEPOLBAN = OLD.ID_UCEPOLBAN;
8           DELETE FROM UCEVFAKVYU WHERE ID_UCEPOLBAN = OLD.ID_UCEPOLBAN;
9           DELETE FROM UCEBANPOD WHERE ID_UCEPOLBAN = OLD.ID_UCEPOLBAN;
10
11          FOR qNAJAVPIPR IN ( SELECT ID_NAJAVPIPR
12                FROM NAJAVPIPR
13                WHERE ID_UCEPOLBAN = OLD.ID_UCEPOLBAN )
14          LOOP
15            UPDATE NAJAVPIPR
16              SET ID_UCEPOLBAN  = NULL
17              WHERE ID_NAJAVPIPR = qNAJAVPIPR.ID_NAJAVPIPR;
18          END LOOP;
19
20
21      RETURN OLD;
22      end
23      $function$
</pre>

**Comment by darold** [comment]
Sorry, I've forgotten case sensitivity again. Fixed with commit 597e056.

**Comment by okbob** [comment]
Partial success. Still missing control variable for FOR cycle:
<pre>
TRIGGER "IDES_JMMAJ".CISTON_BD BEFORE DELETE
ON  CISTON
FOR EACH ROW

BEGIN
       FOR qClevon IN
        ( SELECT ID_CLEVON  FROM CLEVON
              WHERE ID_CISTON = :old.ID_CISTON )
       LOOP
         UPDATE CLEVON SET ID_CISTON=NULL WHERE ID_CLEVON=qClevon.ID_CLEVON;
       END LOOP;
       --- Clevosozad
        FOR qCLEVOSOZAD IN
        ( SELECT ID_CLEVOSOZAD  FROM CLEVOSOZAD
              WHERE ID_CISTON = :old.ID_CISTON )
       LOOP
         UPDATE CLEVOSOZAD SET ID_CISTON=NULL WHERE ID_CLEVOSOZAD=qCLEVOSOZAD.ID_CLEVOSOZAD;
       END LOOP;

END CISTON_BD;
</pre>

Ora2pg:
<pre>
        CREATE OR REPLACE FUNCTION public.trigger_fct_ciston_bd()
         RETURNS trigger
         LANGUAGE plpgsql
         SECURITY DEFINER
1       AS $function$
2       BEGIN
3              FOR qClevon IN ( SELECT ID_CLEVON  FROM CLEVON
4                     WHERE ID_CISTON = OLD.ID_CISTON )
5              LOOP
6                UPDATE CLEVON SET ID_CISTON = NULL WHERE ID_CLEVON=qClevon.ID_CLEVON;
7              END LOOP;
8              --- Clevosozad
9               FOR qCLEVOSOZAD IN ( SELECT ID_CLEVOSOZAD  FROM CLEVOSOZAD
10                    WHERE ID_CISTON = OLD.ID_CISTON )
11             LOOP
12               UPDATE CLEVOSOZAD SET ID_CISTON = NULL WHERE ID_CLEVOSOZAD=qCLEVOSOZAD.ID_CLEVOSOZAD;
13             END LOOP;
14
15      RETURN OLD;
16      END
17      $function$
</pre>

**Comment by darold** [comment]
Right, commit cfc1993 fix this issue when there is no DECLARE section.

**Comment by okbob** [comment]
It is fixed now, thank you
