### ISSUE TITLE
Dublicate partition name error

### ISSUE THREAD

**Issue by denoley** [darold/ora2pg#689]
There are 2 partitioned tables in In Oracle.

```
CREATE TABLE KBLN_INFO_PART_SUBPART ( 
    INFO_ID                     VARCHAR2(25 CHAR) DEFAULT substr(sys_guid(),1,25) NOT NULL,  
    BLANK_SERIES                VARCHAR2(50 CHAR) NOT NULL,
    BLANK_NUMBER                VARCHAR2(50 CHAR) NOT NULL,  
    BLANK_NUMBER_INT            NUMBER Generated Always as (TO_NUMBER(BLANK_NUMBER)))	
	PARTITION BY RANGE (BLANK_NUMBER_INT) INTERVAL(10000) 
	SUBPARTITION BY HASH (BLANK_SERIES) subpartitions 4
		(PARTITION P0 VALUES LESS THAN (10000))
	enable row movement;
	
CREATE TABLE KBLN_INFO_PART_ONLY ( 
    INFO_ID                     VARCHAR2(25 CHAR) DEFAULT substr(sys_guid(),1,25) NOT NULL,  
    BLANK_SERIES                VARCHAR2(50 CHAR) NOT NULL,
    BLANK_NUMBER                VARCHAR2(50 CHAR) NOT NULL,  
    BLANK_NUMBER_INT            NUMBER Generated Always as (TO_NUMBER(BLANK_NUMBER)))	
	PARTITION BY RANGE (BLANK_NUMBER_INT) INTERVAL(10000) 	
		(PARTITION P0 VALUES LESS THAN (10000))
	enable row movement;
```

Ora2pg generates DDL for tables:
```
CREATE TABLE kbln_info_part_only (
	info_id varchar(25) NOT NULL DEFAULT 'substr(uuid_generate_v4(),1,25)',
	blank_series varchar(50) NOT NULL,
	blank_number varchar(50) NOT NULL,
	blank_number_int numeric
) PARTITION BY RANGE (blank_number_int) ;

CREATE TABLE kbln_info_part_subpart (
	info_id varchar(25) NOT NULL DEFAULT 'substr(uuid_generate_v4(),1,25)',
	blank_series varchar(50) NOT NULL,
	blank_number varchar(50) NOT NULL,
	blank_number_int numeric
) PARTITION BY RANGE (blank_number_int) ;

```

and for partitions:

```
CREATE TABLE p0 PARTITION OF kbln_info_part_only
FOR VALUES FROM (MINVALUE) TO (10000);
CREATE TABLE sys_p18390 PARTITION OF kbln_info_part_only
FOR VALUES FROM (10000) TO (20000);
...
CREATE TABLE p0 PARTITION OF kbln_info_part_subpart
FOR VALUES FROM (MINVALUE) TO (10000)
PARTITION BY HASH (blank_series);
CREATE TABLE p0_sys_subp18201 PARTITION OF p0
FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE p0_sys_subp18202 PARTITION OF p0
FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE p0_sys_subp18203 PARTITION OF p0
FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE p0_sys_subp18204 PARTITION OF p0
FOR VALUES WITH (MODULUS 4, REMAINDER 3);
CREATE TABLE sys_p18389 PARTITION OF kbln_info_part_subpart
FOR VALUES FROM (10000) TO (20000)
PARTITION BY HASH (blank_series);
```

As you see, DDL for partitions of 2nd table would produce error:

```
CREATE TABLE p0 PARTITION OF kbln_info_part_only FOR VALUES FROM (MINVALUE) TO (10000); -- OK
...
CREATE TABLE p0 PARTITION OF kbln_info_part_subpart FOR VALUES FROM (MINVALUE) TO (10000) PARTITION BY HASH (blank_series); -- ERROR!!!
```

But in Orcale it's a normal situation when partitions have equvalent names.

**Comment by darold** [comment]
Right, this is not possible in PostgreSQL, table/partition names must be unique. Ora2Pg has a workaround for that, enable PREFIX_PARTITION in ora2pg.conf. Please upgrade to latest development code as last commit a9af354 fixes a bug in subpartition renaming.

**Comment by denoley** [comment]
```
[bash-4.2$ git log -2
commit a9af35490fc3a284f4c94d038477bad5314a0bb3
Author: Gilles Darold <gilles@darold.net>
Date:   Fri Sep 7 12:45:13 2018 +0200

    Fix subpartition prefix name.

commit ae749d78947a70e8885d52abdfac887fcdf6c59e
Author: Gilles Darold <gilles@darold.net>
Date:   Fri Sep 7 12:10:04 2018 +0200

    Prevent duplicate index with primary key on partition.](url)

bash-4.2$ md5sum Ora2Pg.pm
fbc9eb9c492fb62cf9a3efe9b8055d4d  Ora2Pg.pm
```

I set PREFIX_PARTITION 1 and run ora2pg.
DDL:

```
CREATE TABLE kbln_info_p0 PARTITION OF kbln_info
FOR VALUES FROM (MINVALUE) TO (500000)
PARTITION BY HASH (blank_series);
CREATE TABLE kbln_info_sys_subp11395 PARTITION OF p0
FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE kbln_info_sys_subp11396 PARTITION OF p0
FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE kbln_info_sys_subp11397 PARTITION OF p0
FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE kbln_info_sys_subp11398 PARTITION OF p0
FOR VALUES WITH (MODULUS 4, REMAINDER 3);
```

DDL for hash subpartition still reference on p0, but it doesn't exists.

**Comment by darold** [comment]
Fixed in last commits with a bug introduced in previous patches that was duplicating multiple time the range clause.

**Comment by denoley** [comment]
```
-bash-4.2$ git log -2
commit 6993e5d0364c91e55d903b85e2cc11dbdb56b95b
Merge: 2bbe179 8de4a30
Author: Gilles Darold <gilles@darold.net>
Date:   Mon Sep 10 08:43:01 2018 +0200

    Merge pull request #687 from Maxime2/keep-pkey-names

    Enforce KEEP_PKEY_NAMES=1 when USE_TABLESPACE is enabled

commit 8de4a30ad48d768b11f6d92469f7d4214a68cfd4
Author: Maxim Zakharov <dp.maxime@gmail.com>
Date:   Wed Sep 5 18:08:11 2018 +1000

    enforce KEEP_PKEY_NAMES when USE_TABLESPACE is enabled

bash-4.2$ md5sum Ora2Pg.pm
0591539a50717e15ec473e04ab973222  Ora2Pg.pm
```

With mixed partitions error still present. Oracle DDL:

```
CREATE TABLE KBLN_INFO_PART_SUBPART ( 
    INFO_ID                     VARCHAR2(25 CHAR) DEFAULT substr(sys_guid(),1,25) NOT NULL,  
    BLANK_SERIES                VARCHAR2(50 CHAR) NOT NULL,
    BLANK_NUMBER                VARCHAR2(50 CHAR) NOT NULL,  
    BLANK_NUMBER_INT            NUMBER Generated Always as (TO_NUMBER(BLANK_NUMBER)))	
	PARTITION BY RANGE (BLANK_NUMBER_INT) INTERVAL(10000) 
	SUBPARTITION BY HASH (BLANK_SERIES) subpartitions 4
		(PARTITION P0 VALUES LESS THAN (10000))
	enable row movement;
```

Ora2Pg DDL:
table.sql:
```
CREATE TABLE kbln_info_part_subpart (
info_id varchar(25) NOT NULL DEFAULT 'substr(uuid_generate_v4(),1,25)',
blank_series varchar(50) NOT NULL,
blank_number varchar(50) NOT NULL,
blank_number_int numeric
) PARTITION BY RANGE (blank_number_int) ;
```

partition.sql:
```
CREATE TABLE kbln_info_part_subpart_p0 PARTITION OF kbln_info_part_subpart
FOR VALUES FROM (MINVALUE) TO (10000)
PARTITION BY HASH (blank_series);
CREATE TABLE kbln_info_part_subpart_sys_subp18201 PARTITION OF p0
FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE kbln_info_part_subpart_sys_subp18202 PARTITION OF p0
FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE kbln_info_part_subpart_sys_subp18203 PARTITION OF p0
FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE kbln_info_part_subpart_sys_subp18204 PARTITION OF p0
FOR VALUES WITH (MODULUS 4, REMAINDER 3);
CREATE TABLE kbln_info_part_subpart_sys_p18389 PARTITION OF kbln_info_part_subpart
FOR VALUES FROM (10000) TO (20000)
PARTITION BY HASH (blank_series);
CREATE TABLE kbln_info_part_subpart_sys_subp18385 PARTITION OF sys_p18389
FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE kbln_info_part_subpart_sys_subp18386 PARTITION OF sys_p18389
FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE kbln_info_part_subpart_sys_subp18387 PARTITION OF sys_p18389
FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE kbln_info_part_subpart_sys_subp18388 PARTITION OF sys_p18389
FOR VALUES WITH (MODULUS 4, REMAINDER 3);
...
```

**Comment by darold** [comment]
This is fixed:
```
CREATE TABLE kbln_info_part_subpart_p0 PARTITION OF kbln_info_part_subpart
FOR VALUES FROM (MINVALUE) TO (10000)
PARTITION BY HASH (blank_series);
CREATE TABLE kbln_info_part_subpart_p0_sys_subp1026 PARTITION OF kbln_info_part_subpart_p0
FOR VALUES WITH (MODULUS 4, REMAINDER 0);
CREATE TABLE kbln_info_part_subpart_p0_sys_subp1027 PARTITION OF kbln_info_part_subpart_p0
FOR VALUES WITH (MODULUS 4, REMAINDER 1);
CREATE TABLE kbln_info_part_subpart_p0_sys_subp1028 PARTITION OF kbln_info_part_subpart_p0
FOR VALUES WITH (MODULUS 4, REMAINDER 2);
CREATE TABLE kbln_info_part_subpart_p0_sys_subp1029 PARTITION OF kbln_info_part_subpart_p0
```
