### ISSUE TITLE
Out of Memory during SHOW_REPORT

### ISSUE THREAD

**Issue by Pietervanhove** [darold/ora2pg#864]
Hi,

I'm trying to assess an Oracle schema but unfortunately the process always runs out of memory.
I run the following statement:

ora2pg -t SHOW_REPORT --estimate_cost -c ora2pg.conf --dump_as_html > report.html
It runs for a while and then stops with "Out of Memory".

I have already increased the memory of the VM to 256 GB of RAM but still the same issue... We have also created a swapfile as bit as the memory size but still the same issue...

Any ideas?

Best Regards
Pieter

**Comment by darold** [comment]
Odd, with 256GB you should not have OOM. You could limit the assessment to a particular schema and repeat it for all schemas, guessing that you have not set the SCHEMA directive in ora2pg.conf or use the `--namespace` option.

**Comment by Pietervanhove** [comment]
Hi,

Thank you for your reply.
We have set the SCHEMA in the ora2pg.conf file but still the same issue.
Here is some extra information about the schema

  *   1433 tables
  *   508 indexes
  *   1154 procedures and functions (4.772.310 Byte source code)
  *   741 views
  *   384 trigger
  *   5 sequences
  *   3201 constraints

Best Regards
Pieter

**Comment by darold** [comment]
Are you using latest development code ( git clone or `https://github.com/darold/ora2pg/archive/master.zip`)?

What dmesg reports about the OOM event and what is the result of command: `sysctl -a 2>/dev/null | grep overcommit`?

**Comment by Pietervanhove** [comment]
Hi Gilles,

The version of ora2pg is 20.0. The output of the command sysctl command is:

vm.nr_overcommit_hugepages = 0
vm.overcommit_kbytes = 0
vm.overcommit_memory = 2
vm.overcommit_ratio = 99

The dmesg output did not bring any insights. The error message still is: panic: memory wrap at /usr/local/share/perl/5.26.1/Ora2Pg/PLSQL.pm line 2937.EW

Best Regards
Pieter

**Comment by darold** [comment]
Ok, the error line number reported show me that you are not using latest development code. 

Override your installation using:
```
 wget https://github.com/darold/ora2pg/archive/master.zip
unzip master.zip
cd ora2pg-master/
perl Makefile.PL
make
sudo make install
```
then restart the ora2pg command and report the new error message if still present.

**Comment by AwdotiaRomanowna** [comment]
maybe that's the reason? https://github.com/perl/perl5/issues/16960

**Comment by Pietervanhove** [comment]
Hi,

We just did another try without the pipe and again the same error…

Pieter

**Comment by darold** [comment]
A try with an older Perl version would confirm the problem, using perlbrew it is easy to work with different version of Perl.

**Comment by darold** [comment]
Saying that, it is impossible that looking at definition of 
  *   1433 tables
  *   508 indexes
  *   1154 procedures and functions (4.772.310 Byte source code)
  *   741 views
  *   384 trigger
  *   5 sequences
  *   3201 constraints

fills 256GB of memory. If I find time I will include a memory footprint report during the exports to see OIra2Pg memory consumption. On my side the only OOM I have experienced is during data export with a too high value of DATA_LIMIT+multiprocess for the server memory and also when trying to run a migration on a <8GB instance.

**Comment by berenguel** [comment]
Hi Darold
With regards to the same issue, I did an interesting test. I went to C:\DBD-Oracle-1.80\DBD-Oracle-1.80\lib\DBD\Oracle.pm and replace all ORDER BY clauses by $SQL .= "  \n";
The assessment of the schema Pieter mentioned it did finish, indeed, without Out of Memory, however, the HTML was all messed up.
As I have no PERL skills whatsoever, my conclusion was that the ORDER BYs may be the root cause of the "out of memory" in my humble opinion.
I am attaching the before and after file. 
Don't know if it helps, but I think the problem may be the "sorting size" (the schema Pieter is assessing has tens of thousands of rows if you consider the queries DBD is triggering")

*** there were original .pm files, I just changed the extension to .txt so I could attach it here.


[Oracle_bkp2.txt](https://github.com/darold/ora2pg/files/4695889/Oracle_bkp2.txt)
[Oracle.txt](https://github.com/darold/ora2pg/files/4695890/Oracle.txt)

**Comment by darold** [comment]
Hi,

I have already deactivated all unnecessary ORDER BY clause in commit 18ac481 remaining ones are required but I could have miss some clauses. However this can not be the source of the OOM because the ORDER BY clause is executed by Oracle not at Ora2Pg Perl code. In the Ora2Pg/Perl point of view this result in the exact same number of rows to process. So unless the Out of memory message is reported by the Oracle database the problem is not here. In other term if you don't have the OOM after this change this is because not everything is executed normally which explain the messed up report :-)

I have told to Pieter that on my Linux box the assessment with 15000 tables, etc.. doesn't take more that 1 GB of RAM. After more though I asking myself if you are not using e 32bit version of Perl or of the Oracle client. Can you confirm that they are both 64bit version?

The other possible reason is a kind of infinite loop in the regexps during PL/SQL or VIEW assessment that makes a variable size increasing at each loop. If a 32bit version is not in use I really think this is the reason. But without looking at the processed Oracle SQL or PL/SQL code I'm afraid I can not help much more.

**Comment by berenguel** [comment]
Hi, thanks for the quick response I confirm we are running this on 64 bits environment. Pieter and I did not have the time to test this on a non-Windows VM. Our windows VM is Windows Server 2016 64 Bits, Strawberry Perl 5.28-64 bits.
I will give it a go on my Linux VM (Oracle Linux) over the weekend and will let you know.
Thanks!

**Comment by nracmre** [comment]
Hello, I have the exact same error. I'm running ora2pg on a 64 bits Windows with Strawberry Perl 5.26.3.1 64 bits (I tried with the 5.30.2.1 version). During the firsts steps everything is fine but when I got "14/14 objects types (100.0%) inspecting object VIEW", the memory increases very fast and I got "Out of memory !".
Do you have any update on this topic ?
![image](https://user-images.githubusercontent.com/28649510/85578820-a8870200-b63a-11ea-824b-20899805ea70.png)

**Comment by darold** [comment]
Give a try on a Linux box.

**Comment by rdachord** [comment]
We have the exact same problem on Windows w/ 24 GB and Linux with 64 GB with a similar number of objects.

**Comment by darold** [comment]
Yes, I think there is definitively a problem but on my side I have tried with a huge amount of objects without being able to reproduce the issue. There is probably at some point something entering an infinite loop that filled the memory but as SHOW_REPORT use the same code as objects export you should be able to reproduce the problem when exporting the object individually, which doesn't seem to be the case.

I'm waiting for someone that is facing this problem and will be able to debug the SHOW_REPORT action and send me a fix for this issue, otherwise we have to wait that I'm facing it which could not come before a long time.

**Comment by darold** [comment]
FYI, I have just pushed a fix 342a83e for an infinite loop in global variable package extraction that could be the cause of a OOM by appending to a Perl variable infinitely. If some of you @berenguel , @rdachord, @Pietervanhove can try to reproduce this OOM using latest development code this will be helpful to know if the problem is solved or not.

**Comment by rdachord** [comment]
I still encounter the out of memory error with our database:

C:\ora2pg_output>Ora2pg -t SHOW_REPORT --debug --log ./ora2pg_out_201005.txt --dump_as_html --estimate_cost -L 1000 >./report_customer201005.html
Reporting Oracle Content...
Looking at Oracle server version...
Looking at Oracle database size...
Looking at Oracle defined objects...
        Found 356 valid and 0 invalid object FUNCTION
        Found 1499 valid and 0 invalid object INDEX
        Found 38 valid and 0 invalid object INDEX PARTITION
        Found 23 valid and 0 invalid object JOB
        Found 18 valid and 19 invalid object MATERIALIZED VIEW
        Found 105 valid and 0 invalid object PACKAGE
        Found 101 valid and 2 invalid object PACKAGE BODY
        Found 230 valid and 0 invalid object PROCEDURE
        Found 200 valid and 0 invalid object SEQUENCE
        Found 835 valid and 0 invalid object TABLE
        Found 38 valid and 0 invalid object TABLE PARTITION
        Found 483 valid and 0 invalid object TRIGGER
        Found 713 valid and 0 invalid object TYPE
        Found 1674 valid and 0 invalid object VIEW
Looking at table definition...
Looking at views definition...
Looking at database links...
        Found 0 DATABASE LINK.
Looking at jobs...
        Found 23 JOB.
Looking at synonyms...
        Found 6207 SYNONYM.
Looking at global temporary table...
        Found 51 GLOBAL TEMPORARY TABLE.
Looking at encrypted columns...
        Found 0 encrypted column.
Looking at identity columns...
        Found 0 identity column.
Building report for object DATABASE LINK...
Building report for object FUNCTION...
Building report for object GLOBAL TEMPORARY TABLE...
Building report for object INDEX...
Building report for object INDEX PARTITION...
Building report for object JOB...
Building report for object MATERIALIZED VIEW...
Building report for object PACKAGE BODY...
Building report for object PROCEDURE...
Building report for object SEQUENCE...
Building report for object SYNONYM...
Building report for object TABLE...
Building report for object TABLE PARTITION...
Building report for object TRIGGER...
Building report for object TYPE...
Building report for object VIEW...
Out of memory!

C:\ora2pg_output>

Ron Achord
Senior Software Engineer | ron.achord@incora.com | T: +1 512-519-3914
Incora | 12708 Riata Vista Circle Suite B-100 | Austin, Texas 78727 | incora.com
[A picture containing clipart  Description automatically generated]<http://www.incora.com/>
[A picture containing clipart  Description automatically generated]<https://www.linkedin.com/company/incoraglobal/>
[A picture containing animal  Description automatically generated]<https://twitter.com/incoraglobal>
[cid:image009.jpg@01D69B4A.8F8DAC00]<https://www.facebook.com/incoraglobal/>

**Comment by darold** [comment]
This weeks I have exported several schemes with huge number of objects without any issues. My host has 32GB of memory and the Oracle VM is defined with 4 CPU and 12 GB of memory. I have never encountered an OOM while extracting the assessment reports or the DDL export.

I'm closing this issue as not reproducible.
